# Generated by Django 3.2.3 on 2021-06-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address_1', models.CharField(default='123 Street Road', max_length=100, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('city', models.CharField(default='Zanesville', max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='Zip Code')),
                ('state', models.CharField(default='Minnesota', max_length=100, verbose_name='State')),
                ('country', models.CharField(default='Minnesota', max_length=100, verbose_name='State')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
