# Generated by Django 3.2.3 on 2021-06-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(default='United States of America', max_length=100, verbose_name='Country'),
        ),
    ]
