# Generated by Django 3.2.3 on 2021-06-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becomeahost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='host',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='host',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
