# Generated by Django 3.2.3 on 2021-06-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becomeahost', '0002_auto_20210603_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='availability',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
